### ISSUE TITLE
Can you provide the trained weight file?

### ISSUE THREAD

**Issue by qi657** [littlebeen/Diffusion-Enhancement-for-CR#1]
Your work is very interesting, could you please provide your trained weights file (.pth) for easy and direct viewing of the results?

**Comment by littlebeen** [comment]
The pre-train model is uploaded as your request! Hope my work could help you. I would appreciate it if you could give me a star! :)

**Comment by qi657** [comment]
thank you. 
---- Replied Message ----
***@***.***>Date04/02/2024 16:50 ***@***.***> CcChq ***@***.***>,
***@***.***>SubjectRe: [littlebeen/Diffusion-Enhancement-for-CR] Can you provide the trained weight file? (Issue #1)
The pre-train model is uploaded as your request! Hope my work could help you.
