### ISSUE TITLE
pretrained_model

### ISSUE THREAD

**Issue by mboumahdi** [littlebeen/Diffusion-Enhancement-for-CR#3]
Hello can you share the weight of the models you used for the paper, I have problem downloading it from Baido, could you upload it in another platfrom 
Thank you

**Comment by littlebeen** [comment]
https://huggingface.co/littlebeen/DE/tree/main

**Comment by mboumahdi** [comment]
There is no model available yet, it shows 404 not found

**Comment by littlebeen** [comment]
Where are u from? If you live in chinese, you need to open vpn to visit this website. So I hope you could use Baidu. If you are not, this website is suitable for you.

**Comment by mboumahdi** [comment]
I'm outside China, I guess the model in huggingFace is still private, because I can't see It in the link. I think you should put it public. Thank you

**Comment by littlebeen** [comment]
This is public now.

**Comment by mboumahdi** [comment]
Now I have it, thank you
