### ISSUE TITLE
The thin cloud removal effect is almost zero

### ISSUE THREAD

**Issue by SueZhang2000** [littlebeen/Diffusion-Enhancement-for-CR#6]
I used the pre-trained model weights you provided and the code ran smoothly, but the test results only changed the color of the original cloud RICE2 image and did not remove the effect. Is it a weight issue?
![22SR](https://github.com/user-attachments/assets/c367cc5b-0cf8-4ff6-b896-28a8d948bda6)

**Comment by SueZhang2000** [comment]
are you the author? It looks like a virus

**Comment by littlebeen** [comment]
Download the pretain e2e model (mdsa/mn as your need) and put it into guided_diffusion/couldnet/mdsa/pretrain or guided_diffusion/couldnet/mn/pretrain. The model could be found at https://pan.baidu.com/s/1lyKRG67AxM5SZEj3mhTKWA code:bean

You could choose the appropriate pretrain model as your need (Which model You want to train or test based on? memorynet or mdsa?). Must be done before training and testing

**Comment by littlebeen** [comment]
I have updated the code structure and readme. Hope it could help you!

**Comment by SueZhang2000** [comment]
thank you so much! I'll try it now

**Comment by SueZhang2000** [comment]
DONE ! thank you so much !!!
